apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/demo13-javaee-mysql-net: "true"
        io.kompose.service: app
    spec:
      containers:
        - image: khailqd81/demo-app
          name: app
          ports:
            - containerPort: 8080
              hostPort: 8080
              protocol: TCP
            - containerPort: 9990
              hostPort: 9990
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
